# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 28391af999eda8d581bc18242765b7b616eae94363d4074f6e765296b30628ebb0156586dd5c824c568baba594a7f8697a103e4c68773eeb3d2f04c38fecb9ac

test:
  secret_key_base: 2a4a0a31f94d6f61c57796c96014909e2c05c04a6735864c80be6c0e755550cd1aebccae34cc58d95f4507a89ab90b8d8f9e291823f7f4570a925ac00bdfb9b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
